// CRM action types

export const CRM_SET_VIEW = 'CRM_SET_VIEW';
export const CRM_SELECT_CLIENT = 'CRM_SELECT_CLIENT';
export const CRM_ADD_CLIENT = 'CRM_ADD_CLIENT';
export const CRM_UPDATE_CLIENT = 'CRM_UPDATE_CLIENT';
export const CRM_SET_SEARCH = 'CRM_SET_SEARCH';
export const CRM_SET_STAGE_FILTER = 'CRM_SET_STAGE_FILTER';
export const CRM_ADD_NOTE = 'CRM_ADD_NOTE';
export const CRM_ADD_TRANSACTION = 'CRM_ADD_TRANSACTION';
export const CRM_DELETE_CLIENT = 'CRM_DELETE_CLIENT';
export const CRM_SET_REP_FILTER = 'CRM_SET_REP_FILTER';
export const CRM_IMPORT_CLIENTS = 'CRM_IMPORT_CLIENTS';

// Broker CRM action types
export const BROKER_SET_VIEW = 'BROKER_SET_VIEW';

// KYC
export const BROKER_APPROVE_KYC = 'BROKER_APPROVE_KYC';
export const BROKER_REJECT_KYC = 'BROKER_REJECT_KYC';
export const BROKER_REQUEST_KYC_DOCS = 'BROKER_REQUEST_KYC_DOCS';

// Trading Accounts
export const BROKER_CREATE_TRADING_ACCOUNT = 'BROKER_CREATE_TRADING_ACCOUNT';
export const BROKER_UPDATE_TRADING_ACCOUNT = 'BROKER_UPDATE_TRADING_ACCOUNT';
export const BROKER_DISABLE_TRADING_ACCOUNT = 'BROKER_DISABLE_TRADING_ACCOUNT';

// Affiliates
export const BROKER_ADD_AFFILIATE = 'BROKER_ADD_AFFILIATE';
export const BROKER_UPDATE_AFFILIATE = 'BROKER_UPDATE_AFFILIATE';

// Tickets
export const BROKER_ADD_TICKET = 'BROKER_ADD_TICKET';
export const BROKER_UPDATE_TICKET = 'BROKER_UPDATE_TICKET';
export const BROKER_REPLY_TICKET = 'BROKER_REPLY_TICKET';
export const BROKER_CLOSE_TICKET = 'BROKER_CLOSE_TICKET';

// Notifications
export const BROKER_ADD_NOTIFICATION = 'BROKER_ADD_NOTIFICATION';
export const BROKER_DISMISS_NOTIFICATION = 'BROKER_DISMISS_NOTIFICATION';
export const BROKER_DISMISS_ALL_NOTIFICATIONS = 'BROKER_DISMISS_ALL_NOTIFICATIONS';

// Settings
export const BROKER_UPDATE_SETTINGS = 'BROKER_UPDATE_SETTINGS';
